//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Virgil.Sync.CLI {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
    ""authorized_by"": ""com.virgilsecurity.identity"",
    ""created_at"": ""2016-05-10T09:58:41+0000"",
    ""data"": null,
    ""hash"": ""UVYK4ft47gFFXcvJoq6CcB5BVOb3b0YB/61Ywg/D/hE3kXSHsRhI6I3mopLJYP3kiMvZoKbyV209oT0tkRk7Iw=="",
    ""id"": ""bd40f248-4f76-4d61-97cf-f74b74e1f0ab"",
    ""identity"": {
        ""created_at"": ""2016-05-10T09:58:41+0000"",
        ""id"": ""49737166-b415-436f-ad67-4f445e3df75e"",
        ""type"": ""email"",
        ""value"": ""virgilclitests@mailinator.com""
    },
    ""public_key"": {
        ""created_at"": ""2016-05-10T09:58:41+0000"",
        ""id"": ""cd806839-a130-4cd9-9d40-05f3ed02de6a"",
        ""public_key"": ""LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZzd0ZRWUhLb1pJemowQ0FRWUtLd1lCQkFHWFZRRUZBUU5DQUFSL01UZzR5VFkzKzZUb2hJSG1FejJkQmJCcQpnck9xV2JTeTZVN2Uyc0lSb0FBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUEKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==""
    }
}")]
        public string VirgilCard {
            get {
                return ((string)(this["VirgilCard"]));
            }
            set {
                this["VirgilCard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-----BEGIN EC PRIVATE KEY-----\r\nMHkCAQEEIF8niPRbHBwnHuPRRXD3cE1Gr0YN8rn+9JJKeMBfh" +
            "GpQoAwGCisGAQQB\r\nl1UBBQGhRANCAAR/MTg4yTY3+6TohIHmEz2dBbBqgrOqWbSy6U7e2sIRoAAAAAA" +
            "A\r\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n-----END EC PRIVATE KEY-----\r\n")]
        public string PrivateKey {
            get {
                return ((string)(this["PrivateKey"]));
            }
            set {
                this["PrivateKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("151132913")]
        public string UserId {
            get {
                return ((string)(this["UserId"]));
            }
            set {
                this["UserId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14c-HsvO9WUAAAAAAAADnzWzvjFvup8vGQolOSkprSz2qKUwJ7EQ_YSVKJjaAmVN")]
        public string AccessToken {
            get {
                return ((string)(this["AccessToken"]));
            }
            set {
                this["AccessToken"] = value;
            }
        }
    }
}
