// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Foundation;

namespace Virgil.Sync.Mac
{
	public partial class VirgilReplaceAnimator : NSObject
	{
		public VirgilReplaceAnimator (IntPtr handle) : base (handle)
		{
		}
	}
}
