// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Virgil.Sync.Mac
{
	public partial class VirgilReplaceSegue : NSStoryboardSegue
	{
		public VirgilReplaceSegue (IntPtr handle) : base (handle)
		{
		}
	}
}
